version: 0.0
os: linux
files:
  - source: /
    destination: /revision
permissions:
  - object: /var/www
    user: ec2-user
    group: ec2-user
hooks:
    AfterInstall:
      - location: update_app.sh
        timout: 6
        runas: ec2-user
    ApplicationStart:
      - location: restart_app.sh
        timout: 6
        runas: ec2-user